#!/bin/bash

VERSION=`cat silabs-pti/VERSION`
TAG=release-${VERSION}

echo "Preparing release with tag $TAG..."
git tag $TAG
if [ $? != 0 ]; then
  echo "This release already exists. You can not create another one. Aborting..."
  exit
fi

echo "Clean files from previous release..."
mkdir -p release
rm -f release/*

echo "Download artifacts from github..."
gh run download -n silabs-pti -D release/

echo "Add jar files without the version in their names..."
cp release/silabs-pti-lib-${VERSION}.jar release/silabs-pti-lib.jar
cp release/silabs-pti-${VERSION}.jar release/silabs-pti.jar

echo "Use gh to create a release."
git push --tags upstream
gh release create $TAG --generate-notes release/*
