#!/bin/bash

VERSION=`cat silabs-pti/VERSION`
TAG=release-${VERSION}

echo "Preparing release with tag $TAG..."
git tag $TAG
if [ $? != 0 ]; then
  echo "This release already exists. You can not create another one. Aborting..."
  exit
fi

echo "Clean everything..."
mkdir -p release
rm -f release/*
./gradlew clean

echo "Build libraries..."
./gradlew all

echo "Copy libraries to release/ folder..."
cp silabs-pti/build/libs/* release/
cp release/silabs-pti-lib-${VERSION}.jar release/silabs-pti-lib.jar
cp release/silabs-pti-${VERSION}.jar release/silabs-pti.jar

echo "Use gh to create a release."
git push --tags upstream
gh release create $TAG --generate-notes release/*
