/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.silabs.pti;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

import com.silabs.pti.util.Time;

class LibraryTest {
    @Test void testSomeLibraryMethod() {
        Time classUnderTest = new Time();
        assertNotNull(classUnderTest);
    }
}
