/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.silabs.pti;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

class MainTest {
    @Test void testCommandLineHelp() {
        Main main = new Main(new String[] {"-?"});
        assertNotNull(main);
        assertTrue(main.cli().shouldExit() );
        assertEquals(1, main.cli().exitCode());
    }
}
